/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mytoolbox_CONSTANTS_H
#define mytoolbox_CONSTANTS_H

#include "mytoolbox_types.h"

namespace mytoolbox {

class mytoolboxConstants {
 public:
  mytoolboxConstants();

  int16_t EARTH_RADIUS;
};

extern const mytoolboxConstants g_mytoolbox_constants;

} // namespace

#endif
