/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MyToolbox.h"
#include "MyToolbox.tcc"

namespace mytoolbox {


MyToolbox_get_distance_args::~MyToolbox_get_distance_args() throw() {
}


MyToolbox_get_distance_pargs::~MyToolbox_get_distance_pargs() throw() {
}


MyToolbox_get_distance_result::~MyToolbox_get_distance_result() throw() {
}


MyToolbox_get_distance_presult::~MyToolbox_get_distance_presult() throw() {
}


MyToolbox_find_occurences_args::~MyToolbox_find_occurences_args() throw() {
}


MyToolbox_find_occurences_pargs::~MyToolbox_find_occurences_pargs() throw() {
}


MyToolbox_find_occurences_result::~MyToolbox_find_occurences_result() throw() {
}


MyToolbox_find_occurences_presult::~MyToolbox_find_occurences_presult() throw() {
}

} // namespace

