import sys, glob
# path for file generated by Apache Thrift Compiler
sys.path.append('gen-py')
# add path where built Apache Thrift libraries are
sys.path.insert(0, glob.glob('thrift-0.9.2/lib/py/build/lib.*')[0])


from myfirst import MyFirstService
from myfirst.ttypes import *
from myfirst.constants import *

from thrift.transport import TSocket
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol
from thrift.server import TServer

class MyFirstHandler:
    def __init__(self):
        pass

    def log(self, filename):
        # implement log here
        pass

    def multiply(self, number1, number2):
        # implement multiply here
        pass

    def get_log_size(self, filename):
        # implement get_log_size here
        pass

handler = MyFirstHandler()
processor = MyFirstService.Processor(handler)
transport = TSocket.TServerSocket(port=8080)
tfactory = TTransport.TBufferedTransportFactory()
pfactory = TBinaryProtocol.TBinaryProtocolFactory()

server = TServer.TSimpleServer(processor, transport, tfactory, pfactory)

server.serve()