import org.apache.thrift.server.TServer;
import org.apache.thrift.server.TServer.Args;
import org.apache.thrift.server.TThreadPoolServer;
import org.apache.thrift.transport.TServerSocket;
import org.apache.thrift.transport.TServerTransport;

// import code generated by Apache Thrift compiler
import myfirst.*;

public class MyFirstServer {

    public static MyFirstHandler handler;

    public static MyFirst.Processor processor;

    public static void main(String [] args) {
        handler = new MyFirstHandler();
        processor = new MyFirst.Processor(handler);

        Runnable server = new Runnable() {
            public void run() {
                myserver(processor);
            }
        };

        new Thread(server).start();
    }

    public static void myserver(MyFirst.Processor processor) {
        TServerTransport serverTransport = new TServerSocket(8080);
        TServer server = new TThreadPoolServer(new TThreadPoolServer.Args(serverTransport).processor(processor));
        server.serve();
    }

}