import org.apache.thrift.TException;

// import code generated by Apache Thrift compiler
import myfirst.*;

public class MyFirstHandler implements MyFirstService.Iface {

    public MyFirstHandler() {
    }


    public void log(String filename) {
        // implementation omitted    
    }

    public int multiply(int number1, int number2) {
        // implementation omitted
    }

    public int get_log_size(String filename) {
        // implementation omitted
    }

}
