# directory with code generated by Apache Thrift
$:.push('gen-rb')
# directory with the Apache Thrift library
$:.unshift 'thrift/lib/rb/lib'

require 'thrift'

require 'my_first_service'

class MyFirstHandler
    def initialize; end

    def log(filename)
      # implement log here
    end

    def multiply(number1, number2)
      # implement multiply here
    end

    def get_log_size(filename)
      # implement get_log_size here
    end

end

handler = MyFirstHandler.new()
processor = MyFirstService::Processor.new(handler)
transport = Thrift::ServerSocket.new(8080)
transportFactory = Thrift::BufferedTransportFactory.new()
server = Thrift::SimpleServer.new(processor, transport, transportFactory)

server.serve()