# directory with code generated by Apache Thrift
$:.push('gen-rb')
# directory with the Apache Thrift library
$:.unshift 'thrift/lib/rb/lib'

require 'thrift'

require 'my_first_service'

transport = Thrift::BufferedTransport.new(Thrift::Socket.new('localhost', 8080))
protocol = Thrift::BinaryProtocol.new(transport)
client = MyFirstService::Client.new(protocol)

transport.open()

client.log("logfile.log")
print client.multiply(14,3)

transport.close()